# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.client import cortex_forge_pb2 as cortex__forge__pb2


class CortexForgeStub(object):
  """── Cortex Forge gRPC Service ─────────────────────────────────────────────
  Exposes model loading, inference, and accelerator monitoring for the
  NVIDIA Jetson AGX Orin ML accelerators (NVDLA, PVA, GPU).

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadModel = channel.unary_unary(
        '/cortexforge.CortexForge/LoadModel',
        request_serializer=cortex__forge__pb2.LoadModelRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.LoadModelResponse.FromString,
        )
    self.UnloadModel = channel.unary_unary(
        '/cortexforge.CortexForge/UnloadModel',
        request_serializer=cortex__forge__pb2.UnloadModelRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.UnloadModelResponse.FromString,
        )
    self.ListModels = channel.unary_unary(
        '/cortexforge.CortexForge/ListModels',
        request_serializer=cortex__forge__pb2.ListModelsRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.ListModelsResponse.FromString,
        )
    self.GetModelInfo = channel.unary_unary(
        '/cortexforge.CortexForge/GetModelInfo',
        request_serializer=cortex__forge__pb2.GetModelInfoRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.GetModelInfoResponse.FromString,
        )
    self.Infer = channel.unary_unary(
        '/cortexforge.CortexForge/Infer',
        request_serializer=cortex__forge__pb2.InferRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.InferResponse.FromString,
        )
    self.InferStream = channel.unary_stream(
        '/cortexforge.CortexForge/InferStream',
        request_serializer=cortex__forge__pb2.InferRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.InferResponse.FromString,
        )
    self.GetMetrics = channel.unary_unary(
        '/cortexforge.CortexForge/GetMetrics',
        request_serializer=cortex__forge__pb2.GetMetricsRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.GetMetricsResponse.FromString,
        )
    self.WatchMetrics = channel.unary_stream(
        '/cortexforge.CortexForge/WatchMetrics',
        request_serializer=cortex__forge__pb2.GetMetricsRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.MetricsSnapshot.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/cortexforge.CortexForge/HealthCheck',
        request_serializer=cortex__forge__pb2.HealthCheckRequest.SerializeToString,
        response_deserializer=cortex__forge__pb2.HealthCheckResponse.FromString,
        )


class CortexForgeServicer(object):
  """── Cortex Forge gRPC Service ─────────────────────────────────────────────
  Exposes model loading, inference, and accelerator monitoring for the
  NVIDIA Jetson AGX Orin ML accelerators (NVDLA, PVA, GPU).

  """

  def LoadModel(self, request, context):
    """Model management
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnloadModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListModels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Infer(self, request, context):
    """Inference
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InferStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMetrics(self, request, context):
    """Monitoring
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WatchMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    """Health
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CortexForgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadModel': grpc.unary_unary_rpc_method_handler(
          servicer.LoadModel,
          request_deserializer=cortex__forge__pb2.LoadModelRequest.FromString,
          response_serializer=cortex__forge__pb2.LoadModelResponse.SerializeToString,
      ),
      'UnloadModel': grpc.unary_unary_rpc_method_handler(
          servicer.UnloadModel,
          request_deserializer=cortex__forge__pb2.UnloadModelRequest.FromString,
          response_serializer=cortex__forge__pb2.UnloadModelResponse.SerializeToString,
      ),
      'ListModels': grpc.unary_unary_rpc_method_handler(
          servicer.ListModels,
          request_deserializer=cortex__forge__pb2.ListModelsRequest.FromString,
          response_serializer=cortex__forge__pb2.ListModelsResponse.SerializeToString,
      ),
      'GetModelInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelInfo,
          request_deserializer=cortex__forge__pb2.GetModelInfoRequest.FromString,
          response_serializer=cortex__forge__pb2.GetModelInfoResponse.SerializeToString,
      ),
      'Infer': grpc.unary_unary_rpc_method_handler(
          servicer.Infer,
          request_deserializer=cortex__forge__pb2.InferRequest.FromString,
          response_serializer=cortex__forge__pb2.InferResponse.SerializeToString,
      ),
      'InferStream': grpc.unary_stream_rpc_method_handler(
          servicer.InferStream,
          request_deserializer=cortex__forge__pb2.InferRequest.FromString,
          response_serializer=cortex__forge__pb2.InferResponse.SerializeToString,
      ),
      'GetMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.GetMetrics,
          request_deserializer=cortex__forge__pb2.GetMetricsRequest.FromString,
          response_serializer=cortex__forge__pb2.GetMetricsResponse.SerializeToString,
      ),
      'WatchMetrics': grpc.unary_stream_rpc_method_handler(
          servicer.WatchMetrics,
          request_deserializer=cortex__forge__pb2.GetMetricsRequest.FromString,
          response_serializer=cortex__forge__pb2.MetricsSnapshot.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=cortex__forge__pb2.HealthCheckRequest.FromString,
          response_serializer=cortex__forge__pb2.HealthCheckResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cortexforge.CortexForge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
